### ISSUE TITLE
Building error dependencies

### ISSUE THREAD

**Issue by Deamonn** [kangarko/Foundation#1]
Building against the latest version gives me the following error

https://pastebin.com/XRAkLpcE

**Comment by nooneplus** [comment]
Those errors are normal.. 

You can try to re-import:
http://prntscr.com/p17otk

you will see progress here:
http://prntscr.com/p17paw

**Comment by Deamonn** [comment]
> Those errors are normal..
> 
> You can try to re-import:
> http://prntscr.com/p17otk
> 
> you will see progress here:
> http://prntscr.com/p17paw

Tried this, build keeps failing. Here's my pom.xml
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    

    
    
    

    

    <groupId>me.deamon</groupId>
    <artifactId>projectmc</artifactId>
    <name>ProjectMC</name>
    <version>1.0.0</version>

    

    
    <properties>

        
        <main.class>me.deamon.ProjectMC</main.class>

        
        <foundation.version>5.0.8</foundation.version>

        
        <java.version>1.8</java.version>

        
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    
    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/groups/public/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
    </repositories>

    
    <dependencies>

        
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>

            
            <version>1.14.3-R0.1-SNAPSHOT</version>

            
            <scope>provided</scope>
        </dependency>

        
        <dependency>
            <groupId>com.github.kangarko</groupId>
            <artifactId>Foundation</artifactId>
            <version>${foundation.version}</version>
            
            <scope>compile</scope>
        </dependency>
    </dependencies>

    
    <build>

        
        <plugins>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                
                <version>3.2.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <finalName>${project.name}-${project.version}</finalName>
                            <artifactSet>
                                <includes>
                                    <include>org.mineacademy:Game*</include>
                                    <include>com.github.kangarko:Foundation*</include>
                                </includes>
                                <excludes>
                                    <exclude>org.mineacademy:GameAPI*</exclude>
                                </excludes>
                            </artifactSet>
                            <relocations>
                                <relocation>
                                    <pattern>org.mineacademy</pattern>
                                    <shadedPattern>${project.groupId}.${project.artifactId}.lib</shadedPattern>
                                    <excludes>
                                        <exclude>org.mineacademy.${project.artifactId}.*</exclude>
                                        <exclude>org.mineacademy.gameapi.*</exclude>
                                        <exclude>org.mineacademy.boss.*</exclude>
                                        <exclude>org.mineacademy.worldeditbridge.*</exclude>
                                    </excludes>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

        
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

</project>`

**Comment by downtoearthdev** [comment]
I use Gradle and have this in the dependency block:
`compile ('com.github.kangarko:Foundation:5.0.8') {
        transitive = false // Too many fucking dependencies, not necessary
    }`

Dunno if Maven has an equivalent

**Comment by kangarko** [comment]
Apology for a super late, totally missed that notification!

Can you access https://bitbucket.org/mineacademy/libraries in your browser? The site seems to be blocked in some countries.

**Comment by FeaturedSpace** [comment]
@Deamonn

**Comment by Deamonn** [comment]
I'm currently on holiday. Unfortunately I am not able to check this however AFAIK the bitbucket website has always been available since I used it too. I have problems with the auth me dependency. Is it possible to turn it off since I dont use it anyways.

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by FeaturedSpace** [comment]
@Deamonn I have a fix for this. In your POM, you must exclude the Dependency from the building process, not just shade it out of the compiled JAR. Alter your Foundation Dependency inside your pom.xml to this:

```java
 <!--
           Import the Foundation library to kickstart our plugin development
       -->
        <dependency>
            <groupId>com.github.kangarko</groupId>
            <artifactId>Foundation</artifactId>
            <version>${foundation.version}</version>
            <!-- Include Foundation and its dependencies. There are exceptions, see shade plugin below -->
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.mineacademy.plugin</groupId>
                    <artifactId>AuthMe</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by kangarko** [comment]
This is strange, not sure why you had to remove just that dependency.

I had a few users complain that their ISP is blocking BitBucket. I am investigating an alternative hosting for the library files.

**Comment by FeaturedSpace** [comment]
As of 5.1.1 this issue has been resolved. If you experience further issues with dependencies, please check your pom.xml and make sure it's foundation-version has been updated properly.

**Comment by kangarko** [comment]
True, closing this.
