### ISSUE TITLE
1.17/1.16.5: hasGsonSupport always null

### ISSUE THREAD

**Issue by plusgithub** [kangarko/Foundation#101]
1.17: Getting NullPointerException error

In the latest (5.9.0) Foundation release. No matter what version I use, 1.16.5 or 1.17, I get the same error of hasGsonSupport is null. The line is: 
`java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "com.cursedplanet.cursedlibrary.lib.fo.remain.nbt.MinecraftVersion.hasGsonSupport" is null`

Whilst the entire stacktrace is below:

https://pastebin.com/uncesney

**Comment by kangarko** [comment]
Thanks, I solved it. In Foundation we require GSON for all plugins. Ancient plugins such as those made for MC 1.7.10 and earlier may use our BungeeChatAPI library to add this.
