### ISSUE TITLE
You say I shall post my mns For update other gui`s

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/Foundation#102]
This is for update hopper gui, It works for 1.16.5 But if I´m not wrong use 1.16.4 similar if not same mns version. Has not try it, but should work for any gui (only change enum from Hopper to an other container). You can play show all from 1*9 to 1*6 gui too (but are only a "gost gui" ). 

I need this in my plugin, so will update for 1.17 and older versions too. now when Foundation not have it for 17.

I dont know it is better way to use IChatBaseComponent, i has not work with BaseComponent so are unfamiliar with it. I have ether way use like this " ' ' " with out ' ' it will only show first world.

Has try add the imports too here (my idea set it to * so have to fix it in manually).
https://pastebin.com/6G3EWPZe

**Comment by kangarko** [comment]
Thanks, yes, we don't have inventory title feature working for 1.17 right now, we will get to this later.

**Comment by broken1arrow** [comment]
> Thanks, yes, we don't have inventory title feature working for 1.17 right now, we will get to this later.

Alright, and  hopper GUI? This code show how i make it work for hoppers (but of you alter Containers.HOPPER to other GUI like chest or i think is something like this for chest default 9xX or Anvil.

**Comment by kangarko** [comment]
Thanks, I finally fixed that!  You can just edit this for yourself for hoppers: https://github.com/kangarko/Foundation/commit/3ee6156289d28516c8cd8ab26dc83f5b27207588

**Comment by broken1arrow** [comment]
> Thanks, I finally fixed that! You can just edit this for yourself for hoppers: [3ee6156](https://github.com/kangarko/Foundation/commit/3ee6156289d28516c8cd8ab26dc83f5b27207588)

Good work :) yea, I will take an look on it, i guess has to download the source to try stuff out.
