### ISSUE TITLE
My version of paged menu

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/Foundation#103]
I will probably work more and fix up the code (but are 100% working).

I have to use instance, in other case I it create new instances every time and I can´t easy access the data. Will clean it up and make it better in future.  

For example make it more customized, should move some of the method to own class (but when make it, I was lazy and not create a second class).

https://pastebin.com/X6nneVqx

This is the core, to create the items inside the paged menu (so it add items on all rows but not last one). 
https://pastebin.com/d9uEbynb

and is not 100% my code has be inspired of someone else code, I cold not use your code because that not work well and hard to collect all code you use for your method (is at least 3 different classes you has use for your paged menu and top of that it branch out in other methods and classes).

**Comment by kangarko** [comment]
Thanks I will look into this!

**Comment by broken1arrow** [comment]
> Thanks I will look into this!

Yea, I working on fix api for everything inside my plugin (what i mean is I will both try cleanup/fix the code and add comments to all methods both inside the api classes and the code). 

But as it is, it working, but has not made it 100% flexibility as your paged menu, has to move the hashmap and other feels to other class because when not use one instance of the class and instead make new instance every time i call  the class it will also create new values (has learn that the hard way). 

one way to fix are static, but I think it the code get cleaner if I split it do different classes and make it more readable and flexible.


And has you some questions how it work, can you ask. I will try to answer any questions.
