### ISSUE TITLE
I don´t know if I shall say is a bug or you has not think on add support for it.

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/Foundation#104]
For one of my containers, you can store in theory 1 million or more items of one type.

And int has a  max limit ofc, so I use BigInteger and it seams work fine, for Serialized and deserialize.

But your toStringFormatted() method not like BigInteger at all (is say it can't recognize the class). 
I solve that problem self and copy over your toString() method to my class :)

I don´t know, perhaps are my need extraordinarily or/and because of the complexity of my plugin.

**Comment by kangarko** [comment]
This is a bug but due to the fact 99.99% of people won't face this problem we're leaving this as wontfix for now.

**Comment by broken1arrow** [comment]
> This is a bug but due to the fact 99.99% of people won't face this problem we're leaving this as wontfix for now.

Yea I think is only me some will run in this this issue :) Has fix an workarund and the hashmap work fine even with BigInteger .
