### ISSUE TITLE
Please provide JavaDocs in the Library so it will be easier to understand methods/classes

### ISSUE THREAD

**Issue by parpar8090** [kangarko/Foundation#105]
Hello, can you please provide JavaDocs in the API so it will be easier to understand methods/classes? I think it can help many people that are confused by some methods. In the JavaDocs, you can explain what the methods do, etc. It's not a mandatory feature, I will be able to code without it.

**Comment by ItzRozzaDev** [comment]
There are comments above most of the methods in foundation. 


Can you give an example of what you mean?

**Comment by AdoNikeOFFICE** [comment]
You can buy course on MineAcademy.org, this API is explained here.

**Comment by VyperzDev** [comment]
> You can buy course on MineAcademy.org, this API is explained here.

I dont think People should have to buy the course in order to understand how the library works

**Comment by parpar8090** [comment]
> You can buy course on MineAcademy.org, this API is explained here.

I have, but the course does not document EVERYTHING, that's why there is a need for a JavaDocs.

> There are comments above most of the methods in foundation.
> 
> Can you give an example of what you mean?

I don't see even a single comment in IntelliJ. However, I just checked the GitHub code and there ARE comments there. For some reason, I can't see them in IntelliJ.
Can someone please explain why I can't see comments?

**Comment by kangarko** [comment]
You don't have to purchase anything to use Foundation. You can download this whole repository from GitHub, place it in the same folder as your plugin and configure your pom.xml to use Foundation as LATEST version (such as what we have for ChatControl Red: https://pastebin.com/Y2CG12Uy). This will force comments to show in your IDE when you hover over Foundation's methods.
