### ISSUE TITLE
1.16.5: Dependency being excluded from the shaded jar - NoClassDefFoundError / ClassNotFoundException

### ISSUE THREAD

**Issue by Zcamt** [kangarko/Foundation#106]
So I'm trying to make a linking system between discord and a server.
For that I've imported JDA which I've played around with before when creating a stand-alone discordbot and I know the dependency I've used works.

However, when I try and launch the plugin, I get the error attached below:
Error in console: https://pastebin.com/YLaeMcZi

I then tried to look at the build process and the messages popping up there, and I realized that it seems like the JDA dependency gets excluded from the shaded jar. 
"[INFO] Excluding net.dv8tion:JDA:jar:4.3.0_277 from the shaded jar."

I'm guessing this is the issue, but how do I fix this.

My pom looks like this:
https://pastebin.com/kHE1SfyA

I know that I'm using an older version of foundation(5.8.0), I've tried using multiple different versions, also the newest ones(including 5.9.6) and it doesn't seem to fix the issue.

**Comment by Zcamt** [comment]
I've tried also using the dependencies through Discordsrv that's already "included" in foundation, but same problem:
https://pastebin.com/8tmtN2sg

**Comment by Zcamt** [comment]
This is both an issue when launching the server from within intellij while using the ant - build.xml file aswell as when I try to export the project as a jar file.

**Comment by kangarko** [comment]
Use the latest Foundation. One way is to download Foundation and edit its, line 211, copy this line and place a new line where you add your dependency to be included. Another way is to edit your pom.xml of your plugin without having to download Foundation and include Foundation as well as your dependency. Here is what we have for ChatControl Red: https://pastebin.com/a2DHVerY
