### ISSUE TITLE
1.8.8: CompMaterial POTATO_ITEM

### ISSUE THREAD

**Issue by BertGarretsen** [kangarko/Foundation#108]
The CompMaterial class does not have a "POTATO_ITEM" entry
minecraft 1.8.8 cannot render the normal "POTATO" item so this will need to be added
the same problem existed with carrots. that was fixed previously though

**Comment by ItzRozzaDev** [comment]
Yh I found this too all that need to change is 
`POTATO("POTATO"),`
`POTATOES("POTATO"),`


To 

`POTATO("POTATO_ITEM"),`
`POTATOES("POTATO_ITEM"),`

**Comment by kangarko** [comment]
Thanks, we have updated CompMaterial completely now. Use 5.10.0
