### ISSUE TITLE
Success, Warning, and Error methods in Common class

### ISSUE THREAD

**Issue by parpar8090** [kangarko/Foundation#109]
## Here are the suggestions:
`Common.log("&aSuccess! "+success)` will be same as `Common.logSuccess(success)`
`Common.log("&eWarning! "+warning)` = `Common.logWarning(warning)`
`Common.log("&cError! "+error)` = `Commong.logError(error)`

Also, same logic applies to `tellSucces`, `tellWarning`, and `tellError `which use `Common.tell(...)` method.

This is not really important, but maybe can be helpful sometimes. I think it's not much and can be easily included in code. :)

**Comment by kangarko** [comment]
Thanks, however you can already use the Messenger class where you call Messenger.success() for example
