### ISSUE TITLE
1.8.8: BossBar API issue

### ISSUE THREAD

**Issue by drzey** [kangarko/Foundation#112]
Okay so when I use BossBar from Foundation it works perfectly fine on newer versions like 1.16.5, but it shows the enderdragon entity on 1.8.8

![2021-08-07_16 28 24](https://user-images.githubusercontent.com/32025749/129484116-5d4b16de-6197-4d2f-9ddd-513ffff6d64c.png)

This is how I set the bossbar.
Remain.sendBossbarTimed(player, "Sheeqz picka", 5, CompBarColor.GREEN, CompBarStyle.SOLID);

**Comment by VyperzDev** [comment]
Weird

**Comment by kangarko** [comment]
Thanks, I moved the dragon down 150 blocks. But we still need to render it in front of the player for the client to draw the bar on such old MC versions.
