### ISSUE TITLE
1.8.8: NoClassDefFoundError WorldInfo

### ISSUE THREAD

**Issue by Obliviated** [kangarko/Foundation#113]
error.txt of plugin: https://pastebin.ubuntu.com/p/Cn4Dmy2JCt/

Firstly, thank you for the plugin. i can't see plugins like this(awesome) recently.

Problem:
When i execute `/boss butcher * test` command manually or from the menu, the console prints error above.

also there are a boss infront of me (so it is in a loaded chunk).

**Comment by kangarko** [comment]
Will fix this in the Boss plugin in 48h.
