### ISSUE TITLE
Use custom domain with jitpack

### ISSUE THREAD

**Issue by Magnum97** [kangarko/Foundation#115]
This is not for Foundation specifically, but may I suggest adding a DNS record so instead of using `com.github.kangarko:Foundation` one could use `org.mineacademy` to get from jitpack. I have done this myself, and I think it is good for both ease of use and looks quite professional. [Here is a link on how to set it up](https://jitpack.io/docs/#custom-domain-name)

**Comment by kangarko** [comment]
Thanks, but that would confuse people because it would essentially make Foundation from disk ambiously having the same path as Foundation from JitPack, we may reconsider this in the future.
