### ISSUE TITLE
private init() in SimpleSettings method should be changed

### ISSUE THREAD

**Issue by parpar8090** [kangarko/Foundation#121]
Hey there, I noticed that to set field in a Settings class requires the _private static void init()_ method, which is called only from reflection, I don't think that was I will suggest is important, but I think it's recommended to just have an abstract method named init in SimpleSettings so that IntelliJ will be able to understand it will be called. Same for the load() methods in YamlStaticConfig.

**Comment by kangarko** [comment]
Thanks, but you'd have to have this method in all subclasses and we'd have to make a bunch of useless extensions. You can just supress this warning for now.
