### ISSUE TITLE
Foundation compile issue

### ISSUE THREAD

**Issue by MrDraqon** [kangarko/Foundation#127]
![image](https://user-images.githubusercontent.com/26146033/144633812-c45e0d58-abcf-4783-b05e-68702cef297f.png)

Cant compile Foundation 5.12.0 look at the image

**Comment by kangarko** [comment]
Try compiling with Java 8 or Java 17

**Comment by MrDraqon** [comment]
> Try compiling with Java 8 or Java 17

Tried 8/16/17 says the same thing

**Comment by MrDraqon** [comment]
Honestly might be an issue with the pom.xml i am using ill try the one from one of your update posts

**Comment by kangarko** [comment]
Investigating asap

**Comment by MrDraqon** [comment]
> Honestly might be an issue with the pom.xml i am using ill try the one from one of your update posts

Yeah not an issue with the pom this is Foundation latest version with no edits

**Comment by kangarko** [comment]
Thanks. Fixed in 5.12.2 :)

**Comment by MrDraqon** [comment]
> Thanks. Fixed in 5.12.2 :)

Awesome thank you!
