### ISSUE TITLE
PlayerUtil.updateInventoryTitle causes gui "crash"

### ISSUE THREAD

**Issue by kiranhart** [kangarko/Foundation#128]
for 1.18, it throws an error and closes the inventory when I navigate to the next page. It only seems to happen when I have the PlayerUtil.updateInventoryTitle(getViewer(), compileTitle0()); bit
https://gyazo.com/d8635b6ae4a1aad6e75056f9c8738564

This is on the latest foundation version

**Comment by kangarko** [comment]
Thanks, I had to disable this temporarily. Super busy atm, I am going to ask if there is anyone who can do the update.

Tried changing the "initMenu" to the "a" method as it's called on 1.18, that gave a blank menu after the animation was over. Needs more digging.

**Comment by kangarko** [comment]
Patched! https://github.com/kangarko/Foundation/commit/407a2b7561517a519c019363db452ff8be025112
