### ISSUE TITLE
1.18.1: PlayerUtil.getPing() No such field ping in EntityPlayer or its super classes

### ISSUE THREAD

**Issue by ethsmith** [kangarko/Foundation#132]
Tested on 1.8.8 and it works fine but most likely due to the package name changes in 1.18, the PlayerUtil.getPing() method can't access a ping field which most likely means a lot of reflection is broken for 1.18 but this is what I have found while following the NMS course.

**Comment by kangarko** [comment]
Just use player.getPing() on Minecraft 1.18 :)

**Comment by ethsmith** [comment]
@kangarko Doesn't that remove the cross compatibility?

**Comment by kangarko** [comment]
You can use something like this:

```
if (MinecraftVersion.atLeast(V.1_18) {
  player.getPing()
} else {
  PlayerUtil.getPlayerPing()
}
```

By the way, Foundation 6 will include this change.
