### ISSUE TITLE
modelData is not being applied somehow

### ISSUE THREAD

**Issue by aaa8881** [kangarko/Foundation#158]
```

            ItemStack test1 = ItemCreator.of(CompMaterial.PAPER).modelData(1).name("test").lore("dd").amount(2).make(); 
            //modelData is not set


            ItemStack test2 = new ItemStack(Material.PAPER,1);
            ItemMeta itemMeta = test2.getItemMeta();
            itemMeta.setCustomModelData(1);
            test2.setItemMeta(itemMeta); 
            //modelData is set


```

paper 1.18.2 , fo6 latest ( compiled from this branch ) 

I looked into the ItemCreator class too but not really sure why this is happening. 

```
if (this.modelData != null && MinecraftVersion.atLeast(V.v1_14))
```
seems to be passing fine :/

**Comment by kangarko** [comment]
It is being applied without Foundation using Bukkit's ItemStack class?

**Comment by aaa8881** [comment]
> It is being applied without Foundation using Bukkit's ItemStack class?

yes, it works fine using bukkit API. I'm really unsure why it happens too.

**Comment by kangarko** [comment]
Thanks, fixed.
