### ISSUE TITLE
1.8.8: Usage Replace

### ISSUE THREAD

**Issue by AdoNikeOFFICE** [kangarko/Foundation#189]
Hello, wouldn't it be possible to put in a command and usage after it? Thanks.

![image](https://user-images.githubusercontent.com/65062119/192525812-321989cb-3e4f-48a9-ba23-700bd95dd780.png)

![image](https://user-images.githubusercontent.com/65062119/192525859-2e6d1501-f08b-4150-8472-53285f2e78c7.png)

In the example I am using Perms built in command.

**Comment by kangarko** [comment]
Added. Just edit the localization file key and place {label} before the end of the key: "Usage: {label} " or something like that (https://github.com/kangarko/Foundation/commit/547d93bc1404441cbae9dbdae59c951b5cff253e)
