### ISSUE TITLE
Another dye issue

### ISSUE THREAD

**Issue by lulu2002** [kangarko/Foundation#2]
`	BLACK_DYE("GRAY_DYE", "INK_SACK", 8),
	BLAST_FURNACE("FURNACE"),
	BLUE_DYE("LIGHT_BLUE_DYE", "INK_SACK", 12),
	BRICK_WALL("COBBLESTONE_WALL"),
	BROWN_DYE("GRAY_DYE", "INK_SACK", 8),
	GREEN_DYE("CACTUS_GREEN", "INK_SACK", 2),`

should be change to

``    BLACK_DYE("INK_SACK", "GRAY_DYE", 8),
    BLAST_FURNACE("FURNACE"),
    BLUE_DYE("INK_SACK", "LIGHT_BLUE_DYE", 12),
    BRICK_WALL("COBBLESTONE_WALL"),
    BROWN_DYE("INK_SACK", "GRAY_DYE", 8),
    GREEN_DYE("INK_SACK", "CACTUS_GREEN", 2),``

INK_SACK should always be legacy name, or it will cause issues while older minecraft version using it.

**Comment by kangarko** [comment]
Thank you, and I apology for a late reply, could you please make a pull request instead?

**Comment by lulu2002** [comment]
Sure, I have finished it.

**Comment by kangarko** [comment]
Thanks
