### ISSUE TITLE
CMI-API has been updated to version 9.3.1.2

### ISSUE THREAD

**Issue by MrCrazys** [kangarko/Foundation#208]
As the title says, the CMI-API GitHub repository has been updated from version 9.0.0.0 to version 9.3.1.2. A lot of new fields and methods have been added. I was just wondering if you could update it for Foundation?

Thanks!

**Comment by kangarko** [comment]
Sure! Updated in Foundation 6.2.9

**Comment by MrCrazys** [comment]
> Sure! Updated in Foundation 6.2.9

Thanks!

**Comment by broken1arrow** [comment]
I can say the 9 version of the api has exist on GitHub for long time. But you need download the source and fix the broken path self and he even did not care to update the api jar ether.

Was recently he finally fix it.

**Comment by MrCrazys** [comment]
> I can say the 9 version of the api has exist on GitHub for long time. But you need download the source and fix the broken path self and he even did not care to update the api jar ether.
> 
> Was recently he finally fix it.

Yeah, because I made an issue on the GitHub. I am friends with one of the admins on the Discord, and I am also a notable member myself. Zrips got around to it around 2 months later though.

**Comment by broken1arrow** [comment]
> > I can say the 9 version of the api has exist on GitHub for long time. But you need download the source and fix the broken path self and he even did not care to update the api jar ether.
> > Was recently he finally fix it.
> 
> Yeah, because I made an issue on the GitHub. I am friends with one of the admins on the Discord, and I am also a notable member myself. Zrips got around to it around 2 months later though.

It has been like this for years. Look on this pull request
https://github.com/Zrips/CMI-API/pull/16#issue-735693881
