### ISSUE TITLE
Update CMI-API version to 9.3.1.5

### ISSUE THREAD

**Issue by MrCrazys** [kangarko/Foundation#210]
Hey again! Just wondering if you could update the CMI-API version in Foundation from 9.3.1.2 to 9.3.1.5? Main update is that there are now move and superficial move methods for holograms. Thanks!

**Comment by kangarko** [comment]
Hey! I am actually really busy at the moment, but our Libraries repository with all the dependencies is publicly available; if you could make a pull request I'd really appreciate it!

https://bitbucket.org/kangarko/libraries

You'd simply place the jar into the org\mineacademy\plugin folder, make sure that it follows the <name>-<version>.jar like the older file and copy over the .pom file as well and edit the version in it. Then simply make a pull request for both Libraries project and Foundation updated pom.xml

Alternatively, you could just use Maven's systemPath method of importing a newer dependency in your own project above Foundation without updating our libraries.

**Comment by MrCrazys** [comment]
> I had some time so I updated it :) An official new version of Foundation will be out by tonight, I just have one more thing to fix there.

Thanks!
