### ISSUE TITLE
API Feature fo Postgresql

### ISSUE THREAD

**Issue by n-tdi** [kangarko/Foundation#219]
1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
Postgresql is a widely popular SQL database. It would be very impactful.
2) What would happen if we won't implement this feature? How's your server being affected?
Well people would have to code their own wrappers for it which takes away from the purpose of Foundation.
3) If suggesting something new - Can the old system be modified/improved instead?
This is more of an addition rather than an improvement.

**Comment by kangarko** [comment]
Thank you. Foundation is open source, I am not available to make this request due to time constrains but you or anyone else is welcome to make a pull request.
