### ISSUE TITLE
SMOOTH_STONE_SLAB missing on CompMaterial

### ISSUE THREAD

**Issue by JoschuaSchneider** [kangarko/Foundation#22]
`CompMaterial.getFromBlock()` returns null for smooth_stone_slabs

I checked the class and discovered that it is missing on the CompMaterial Enum.

I encountered it while getting the material in an BlockPlaceEvent handler, and I did not check it for null.

**How to reproduce**
```java
final CompMaterial testMaterialOne = CompMaterial.fromString("smooth_stone_slab");
final CompMaterial testMaterialTwo = CompMaterial.fromString("stone_slab");

Valid.checkNotNull(testMaterialTwo, "Stone slab is null"); // Does not Throw
Valid.checkNotNull(testMaterialOne, "Smooth stone slab is null"); // Throws
```

**Comment by kangarko** [comment]
Could you please just create a pull request?

**Comment by JoschuaSchneider** [comment]
Opened #24 , thanks for the Reply!
