### ISSUE TITLE
Update NBT-API to 2.11.3

### ISSUE THREAD

**Issue by MrCrazys** [kangarko/Foundation#224]
As the title says, the NBT-API has been updated to 2.11.3. I was wondering if you could update it for Foundation, as there are some missing methods like `setLongArray()` that would be useful to have.

Thanks!

**Comment by kangarko** [comment]
As far as I am aware we should have the latest NBT-API since we do support 1.20.

**Comment by MrCrazys** [comment]
Really? I don't see methods like `setLongArray()`.
![image](https://github.com/kangarko/Foundation/assets/73004328/b1486051-d87d-41da-a2f1-8c0489f3212d)

**Comment by broken1arrow** [comment]
I was in resent contact with the dev and he at least working in performance update. Don't know if it is released yet.

But in that version, you should not do new NBT.

**Comment by kangarko** [comment]
I will check once the other update broken1arrow mentions is out. Thanks for noticing and reporting!

**Comment by MrCrazys** [comment]
Alright, sounds good. Thanks!

**Comment by kangarko** [comment]
Updated!

**Comment by MrCrazys** [comment]
> Updated!

Thanks, Matej, I appreciate it!
