### ISSUE TITLE
Your Suggestion Title

### ISSUE THREAD

**Issue by maliimaloo** [kangarko/Foundation#233]
Hello,

Good evening, I come here to offer you the idea of ​​adding a "SimpleXXX" system which allows you to customize the tabulation system, therefore the display of players in the tab, the message fotter and below, etc.. a bit like the SimpleScoreboard because it is one of the systems that is missing

Thank you for your understanding.

**Comment by kangarko** [comment]
You can use Remain#send such as sendTablist or sendActionBar etc.
