### ISSUE TITLE
Minecraft Version: 1.16.5 - Configuration question // Potential bug?

### ISSUE THREAD

**Issue by xXGamerHDXTv** [kangarko/Foundation#234]
Hello, I would like to use the Points/Mute system from CHC but this system conflicts with my Punishment System (Litebans) Also players are not getting warned/muted by the system Automated.

It also looks like players don't get Warning Points when they break the Swear rule, for example. I've included some screenshots that might explain better what I mean. 

My Config Settings:

⇒ https://ibb.co/KsPJhbL 

⇒ https://ibb.co/sK2qS59

I am honestly not sure what I should have set wrong here, please consider in these screenshots the Integrated Mute System of the plugin is disabled. But players are also not getting muted with the built-in mute system activated.

Here you can see that I get blocked several times by the filter to write certain words, but I do not get the warning messages set in the config and also no mute.

⇒ https://ibb.co/9cyrTbf 

Here you can see that I did not get any warning points for the offensive words.

⇒ https://ibb.co/Fq2FqDm

Here I tried to change something in the config, but this did not fix my problem.

⇒ https://ibb.co/2Fc9Z7d

I'm really wondering what I can do to fix the problem since no one can help me on Discord I was recommended to make a GitHub report and since I'm not sure if it's a wrong config setting I didn't made a bug report. 

Also, litebans:mute is not working as Mute Command.

Thanks for taking the time to look into my Report 
With kind Regards, xXGamerHDX

**Comment by kangarko** [comment]
Please post me your full /chc debug so I can investigate. LiteBans and ChatControl should work together, we execute /lmute each time a player is muted. Warning points should work, I will check it for you.

**Comment by xXGamerHDXTv** [comment]
[debug.zip](https://github.com/kangarko/Foundation/files/12303239/debug.zip)

Here are the log files, I hope this is correct.

**Comment by kangarko** [comment]
You need to add the appropriate operator for your swear group to add the points to the player:

![a](https://i.imgur.com/A3187dC.png)

It worked fine for me after I added this. The number you can change to your liking.
