### ISSUE TITLE
Potentially adding pausing and setTime() functionality to the Countdown class

### ISSUE THREAD

**Issue by Supermrk** [kangarko/Foundation#239]
In some cases, it would be nice to have the ability to set the time on a Countdown, or pause the Countdown entirely. Some use cases could be:

1. If you have a minigame, if a certain number of players join during the lobby countdown, you could set it so there's only 30 seconds remaining to speed the wait time up.
2. Having the ability to pause a Countdown could be useful in sport minigames. If you're familiar with any sports like American Football or Soccer/Football, the game might pause during a Countdown or after a score. This is not yet possible in Foundation's Countdown class.

If this feature was to not be approved and then implemented, I would end up having to make my own implementation for a Countdown. I also believe this could easily be implemented into the current Countdown class.

**Note: I would be willing to implement this myself, I'm just wanting to make sure this is something you would want in Foundation, as it's a decently large feature.**

**Comment by kangarko** [comment]
Thank you. If there is a way to implement 1 and 2 without any breaking API changes (i.e. renaming old methods/parameters) then you are most welcome to do so :) Just make sure to retain backward compatibility. Thanks!
