### ISSUE TITLE
1.16.5: Update foundation from 6.4.7 to 6.5.3 many error occurs on my plugin and older version.

### ISSUE THREAD

**Issue by Deware-PK** [kangarko/Foundation#246]
As title said, my plugin that support server version 1.16.5+ seem doesn't work properly on newest version of foundation so I tried bringing back foundation to version 6.4.7 everything works perfectly except support 1.20.2

Here is error with 6.5.3
![image (2)](https://github.com/kangarko/Foundation/assets/88251253/9e1534a3-69cf-44db-afc5-86e4c8707743)
![image (3)](https://github.com/kangarko/Foundation/assets/88251253/491ca6bf-31a2-4b6d-bb6e-c91cbe62c008)

*Note this class is extends SimpleHolograms
also seem like location#getWorld()#spawn method has been error too don't know why.

To test it with 6.5.3 I've send you my setup.

try the command "callatplayer" /airdropx callatplayer T1 <your name>
In 6.4.7 Hologram should be appears but in 6.5.3 not

also Task scheduler doesn't run properly. You can immediately open the chest instead of wait for delay on 6.5.3 in 6.4.7 should have a message tell you to wait for opening delay while that you cannot open the chest.

6.5.3 with 1.20.2 When you try to take items you can take it unlimited.

Resources:
Setup: 
[Setup.zip](https://github.com/kangarko/Foundation/files/12831070/Setup.zip)
Source code: 
[SRC.zip](https://github.com/kangarko/Foundation/files/12831071/SRC.zip)

**Comment by kangarko** [comment]
@CoobMC Hey Jack! I believe you helped us improve the hologram class, would you please have a look into this one?

**Comment by Supermrk** [comment]
Bukkit doesn't have a awnEntity method with the Consumer in older versions, so you'd either just have to set the values afterwards, or add a check to see whether you're in a new or old version. I could fix this and submit a pull request for it if you'd like?

**Comment by Deware-PK** [comment]
> Bukkit doesn't have a spawnEntity method with the Consumer in older versions, so you'd either just have to set the values afterwards, or add a check to see whether you're in a new or old version. I could fix this and submit a pull request for it if you'd like?

Hello. Everything even spawnEntity works perfectly on foundation 6.4.7 or older. Until I updated to the latest version. many weird things had occurred. I just changed the FO version because I want it to be compatible with the latest MC version.

**Comment by CoobMC** [comment]
Hey @kangarko, I've come across this issue too and changed up the SimpleHologram createEntity method to support versions from 1.8 to the latest. In this class I also made the Hologram implement ConfigSerializable, let me know if you'd like me to add these changes instead to Foundation. I haven't tested it for 1.20.2 but I think it should work.

For the create method it should look like this:
`	private ArmorStand createEntity() {
		final Location location = this.getLastTeleportLocation();
		final ArmorStand armorStand;

		if (MinecraftVersion.atLeast(MinecraftVersion.V.v1_11)) {
			final Consumer<ArmorStand> consumer = stand -> {
				stand.setMarker(true);
				CompProperty.GRAVITY.apply(stand, false);
				stand.setSmall(true);
				stand.setVisible(false);
			};

			armorStand = location.getWorld().spawn(location, ArmorStand.class, consumer);
		} else {
			final ArmorStand stand = location.getWorld().spawn(location, ArmorStand.class);

			CompProperty.GRAVITY.apply(stand, false);
			stand.setVisible(false);
			stand.setMarker(true);
			stand.setSmall(true);

			armorStand = stand;
		}

		return armorStand;
	}`

Hologram: https://pastebin.com/PqmBGUT9

Hope this helps

**Comment by kangarko** [comment]
Thank you, could you please make a pull request @CoobMC ? :)

**Comment by kangarko** [comment]
Closing, @CoobMC let us know when you have the time please. Thanks"!

**Comment by CoobMC** [comment]
Hey @kangarko, sorry for the late reply I was focusing on my exams but I'm done with them. I have pushed the change hope it helps!
