### ISSUE TITLE
Every version: TimeUtil class doesn't work with language file.

### ISSUE THREAD

**Issue by Deware-PK** [kangarko/Foundation#247]
TimeUtil class doesn't work with languages files on the cases section. (Picture below)

![image (4)](https://github.com/kangarko/Foundation/assets/88251253/8a4329a3-7945-44e9-a473-df0cd33e24be)
The method that I used is TimeUtil#formatTimeGeneric(...)

![unnamed](https://github.com/kangarko/Foundation/assets/88251253/ac5675ef-d7dc-4e2e-8604-7e4f9aeec2ec)
![image (5)](https://github.com/kangarko/Foundation/assets/88251253/f9a43526-d530-42c4-baec-644a0dae92cf)

It seem there is no something to change the language.

**Comment by kangarko** [comment]
Right, I dont have time for this and you are the first asking. Just copy over this method into yours and customize it.
