### ISSUE TITLE
FOLIA 1.20.2-R0.1-SNAPSHOT: Method `FoliaGlobalRegionScheduler` is null

### ISSUE THREAD

**Issue by StarozytnySky** [kangarko/Foundation#250]
I wanted run the plugin on the Folia engine, I saw that Foundation added support for it, but I have a problem when I try to use any of the methods from the Common class `runLater`, `runLaterAsync` etc.

Error: https://hastebin.com/share/ijawuvatud.markdown

**Comment by kangarko** [comment]
Please use 6.5.5 and repost the error. 

I assume it happens when you call Common#runLater anywhere?
