### ISSUE TITLE
1.20.1: Plugin not enabling, getting a ton of exceptions!

### ISSUE THREAD

**Issue by deilyyxx** [kangarko/Foundation#261]
My project is using Maven. [**My class where I'm registering a GUI**](https://pastebin.com/YGCF6gnP)
And here's my  [**error log**](https://pastebin.com/Yu1jUjcF).

Thanks!

~deilyyxx...

**Comment by kangarko** [comment]
Did you make your main class extend SimplePlugin instead of JavaPlugin to install Foundation? If yes then check if you're running the latest PlaceholderAPI.
