### ISSUE TITLE
Hi , I just wanted to use foundation api

### ISSUE THREAD

**Issue by ursernameAtmin** [kangarko/Foundation#264]
Hi , I just wanted to use foundation api but when i add these into my pom.xml , it wont done right

repository.
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
./repository

dependency.
            <groupId>${foundation.path}</groupId>
            <artifactId>Foundation</artifactId>
            <version>6.6.2</version>
./dependency

22 Error:
org.mineacademy.plugin:CitizensAPI:pom:2.0.32-05.09.2023
org.mineacademy.plugin:FactionsUUID:pom:1.6.9.5-U0.6.29-b321
.... 20 more plugin

**Comment by kangarko** [comment]
Invalid log. Upload the full compile log alonside your pom.xml to pastebin.com.

You can use my https://github.com/kangarko/PluginTemplate 's pom.xml to import it properly.
