### ISSUE TITLE
1.20.4 Error

### ISSUE THREAD

**Issue by WoodsMc09** [kangarko/Foundation#267]
Hello there, 
I am using the framework in a plugin, and I get this error when I try to use it: https://pastebin.com/YtdsE1fw . I have tried to ask on discord, but haven't gotten answers. I don't think it is my code, as it works perfectly fine on previous versions. If you could either give me an answer as to what I am doing wrong, or fix it, that would be great!
Thanks!

**Comment by WoodsMc09** [comment]
Yes it is.

**Comment by kangarko** [comment]
I have updated NBT-API and all dependencies. Please use Foundation 6.6.6. If that still won't work then unfortunately it's not a Foundation issue since it's called from [NBT-API](https://github.com/tr7zw/Item-NBT-API)
