### ISSUE TITLE
1.20.4: SimplePrompt Error

### ISSUE THREAD

**Issue by EgehanKilicarslan** [kangarko/Foundation#271]
Command: https://pastebin.com/kHB8hb6Q
Error: https://pastebin.com/enLqpKD1

**Comment by kangarko** [comment]
It says" Could not instantiate menu of class com.honemy.learningfoundation.menu.PreferencesMenu, override the method 'newInstance()' or ensure you have a public constructor which takes only one parameter"


Please implement what the error message says
