### ISSUE TITLE
1.20: Getting warning from antivirus (Trojan)

### ISSUE THREAD

**Issue by Lelion62** [kangarko/Foundation#272]
I cant create the jar file because my antivirus says that the worldedit dependency is a trojan and i can't bypass the problem

**Comment by EgehanKilicarslan** [comment]
You should add exclusion to firewall

**Comment by Lelion62** [comment]
Didn't work with bitdefender. But thanks for the help

**Comment by kangarko** [comment]
Exclude it, I am very certain it is a false positive.
