### ISSUE TITLE
1.20.4 : ProtocolLib for enchantments

### ISSUE THREAD

**Issue by steffqxyz** [kangarko/Foundation#277]
Hello, I am doing the Custom Enchant video and I am using Foundaiton. In the video ProtocolLib was mentioned for the item lore, so I added it to the server. Latest spigotmc version, but after restarting the server I am getting this error. I was told to come and open an issue. 

https://pastebin.com/cbvcJa7r - HERE IS THE ERROR

**Comment by kangarko** [comment]
Can you please verify your full startup log whether ProtocolLib has been properly started? Just send it to me and I have a look, thanks.

**Comment by steffqxyz** [comment]
https://pastebin.com/38cHkYq5 Here, thanks!

**Comment by Xefreh** [comment]
do you have depend on protocollib in your plugin.yml file, it seems that foundation cannot find ProtocollibManager because your plugin gets initialized before.
make sure you have this in plugin.yml file:
```yaml
depend: [ProtocolLib]
```

**Comment by steffqxyz** [comment]
It was a soft-depend, changed it to depend, but I get the same exact error.

**Comment by Xefreh** [comment]
do you have logs ?

**Comment by Xefreh** [comment]
mhm ye can you try to use Protocollib 5.1

**Comment by steffqxyz** [comment]
Protocollib 5.1 - https://pastebin.com/PPv50rLt

Not working on 1.20.4 apparently

**Comment by Xefreh** [comment]
mhm ye can you try on 1.20.1 for example ?

**Comment by steffqxyz** [comment]
I used NMS, I'd have to change some methods in the plugin to make it for 1.20.1

**Comment by kangarko** [comment]
What's your /version ?

**Comment by steffqxyz** [comment]
`[17:50:08] [Server thread/INFO]: This server is running CraftBukkit version 4090-Spigot-b754dcc-38b1f49 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)`

**Comment by kangarko** [comment]
Use Paper not Spigot 1.20.4
