### ISSUE TITLE
Minecraft Version: How to use Foregin Key & Index  

### ISSUE THREAD

**Issue by rageyh** [kangarko/Foundation#279]
Hello, i have a question, I am using the library to use mysql database. 
I don't understand how to insert Foregin Keys and Indexes into the table.
Esample: "FOREIGN KEY (sim) REFERENCES SIM(sim),  INDEX idx_sim (sim)"

**Comment by kangarko** [comment]
I do not understand your question. I am afraid we don't provide support with generic SQL commands which is a standalone programming language. You can implement this feature yourself.
