### ISSUE TITLE
Foundation 6.7.9 BUILD FAILURE

### ISSUE THREAD

**Issue by Gryglo** [kangarko/Foundation#280]
![image](https://github.com/kangarko/Foundation/assets/63815382/4c4e6411-f1a7-4b5a-87b3-a5e0715d9b31)
https://jitpack.io/com/github/kangarko/Foundation/6.7.9/build.log

IntelliJ IDEA error: 'com.github.kangarko:Foundation:jar:6.7.9 was not found in https://jitpack.io during a previous attempt.'

**Comment by kangarko** [comment]
Fixed in 6.7.12
