### ISSUE TITLE
1.20.4: SimpleCommandGroup help message only sends one chat line

### ISSUE THREAD

**Issue by BouncingSquirrel** [kangarko/Foundation#281]
Hi, I recently noticed the getHelpHeader() in the SimpleCommandGroup only outputting one smooth chat line. I think it looks a bit weird. Thanks!

**Comment by kangarko** [comment]
You can just override and customize it to your needs.

It looks fine on my end:

![a](https://i.imgur.com/1Ktpotw.png)

And

![b](https://i.imgur.com/d3bEDvs.png)

The smooth line is on the top but not the bottom. That is intended.
