### ISSUE TITLE
1.20.1 Error NoClassDefFoundError

### ISSUE THREAD

**Issue by S1mplicitty** [kangarko/Foundation#282]
My plugin uses your framework, an error appears when starting the server with the plugin: https://pastebin.com/NHb3ZWtX .
Main plugin class extending SimplePlugin.
Pom.xml https://pastebin.com/Td9Qpzfh

**Comment by kangarko** [comment]
Shade Foundation in your plugin's jar as per our README.me instructions. Use the pom.xml from github.com/kangarko/plugintemplate since you also need to configure includesPath which we provide as an example there.
