### ISSUE TITLE
Enchantment display error

### ISSUE THREAD

**Issue by Takivad11** [kangarko/Foundation#283]
Version: 1.20.4

Error: Not exactly getting errors in console, but, i made a new Custom Enchantment, and with ProtocolLib it's displaying the Lore text in game, but if i mix the enchants on a anvil, for example, it will duplicate the text (functionality works perfectly fine, just text error) 

Here you have an example

Before mixing on the anvil:
![image](https://github.com/kangarko/Foundation/assets/167753598/b5aedb77-c96d-4669-a2b5-7179e777cc7b)

After mixing on the anvil:
![image](https://github.com/kangarko/Foundation/assets/167753598/63a096c5-7968-41b9-bd78-ff2b7866a414)

As you can see the Ender Safety II text remains, and after digging into the code a bit, i think the thing is that in the addEnchantmentsLore method you should check if the custom enchant already has some lore written before adding the new one and then deleting it in case it does have it (not sure if it's the actual solution tho)

**Comment by kangarko** [comment]
Thank you for reporting. This is a minor issue I at present have no time for unfortunately. Foundation is open source, contributions are welcome. You are right that it has to do with the addEnchantmentsLore() method in the packets handler class. Feel free to make a pull request.
