### ISSUE TITLE
1.20.1: How to use WorldEdit and other plugins in Foundation?

### ISSUE THREAD

**Issue by xromen** [kangarko/Foundation#293]
I want to use WorldEdit api with Foundation. I downloaded the plugin template from https://github.com/kangarko/PluginTemplate and edited pom.xml
My pom.xml - https://pastebin.com/vvLfY91u
My code in main class - https://pastebin.com/NQycDEaf
Error from console - https://pastebin.com/QnKp41wc
I'm new to plugin programming, please tell me what I'm doing wrong?

**Comment by kangarko** [comment]
Remove

<include>org.mineacademy.plugin:WorldEdit*</include>
                            <include>org.mineacademy.plugin:Vault*</include>

From your pom.xml

Because otherwise you are including a full copy of worldedit in your plugin .jar and it will break

**Comment by xromen** [comment]
I removed these lines and another error appeared https://pastebin.com/sRJ2vEwr.

**Comment by kangarko** [comment]
You also need to delete

 <relocation>
                            <pattern>com.sk89q</pattern>
                            <shadedPattern>${project.groupId}.${project.artifactId}.lib</shadedPattern>
                        </relocation>

Basically rollback your changes in the shade plugin and use the shade from plugintemplate
