### ISSUE TITLE
Foundation 6.8.0 BUILD FAILURE

### ISSUE THREAD

**Issue by LuuckA21** [kangarko/Foundation#294]
![Screenshot 2024-06-08 143316](https://github.com/kangarko/Foundation/assets/50712503/6c2462a8-1793-4054-a826-bcd9dc8d6bd6)

https://jitpack.io/com/github/kangarko/Foundation/6.8.0/build.log

**Comment by kangarko** [comment]
Thanks, will be fixed in the next version.
