### ISSUE TITLE
1.20.1: Getting IOException error

### ISSUE THREAD

**Issue by iHxtch** [kangarko/Foundation#295]
Kindly refer to the below error. I used the latest version of foundation, `6.8.1`, and I am receiving this error. I downgraded to version `6.4.2` because I have an old plugin that uses this same code and now it works fine.

Expected behavior: to create the files if they do not exist
Actual behavior: throws an exception

Error: https://pastebin.com/rhbsBJ89

Code snippet that generates the error: 
![image](https://github.com/kangarko/Foundation/assets/84823076/657db4d6-43c3-464c-949b-2d8db2f415a4)

**Comment by kangarko** [comment]
Thanks. Please upgrade to 6.8.2

**Comment by iHxtch** [comment]
Thanks for the quick fix!
