### ISSUE TITLE
Minecraft Version: 1.21

### ISSUE THREAD

**Issue by Mathildeuh** [kangarko/Foundation#296]
Can't import with gradle

https://hastebin.skyra.pw/oditepicuz.pgsql

https://hastebin.skyra.pw/ufuwejogof.nestedtext

**Comment by kangarko** [comment]
Add this repository too: 

https://bitbucket.org/kangarko/libraries/raw/master/

**Comment by Mathildeuh** [comment]
CustomEnchants:main: Could not find com.mojang:datafixerupper:4.0.26.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.pom
  - https://hub.spigotmc.org/nexus/content/repositories/snapshots/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.pom
  - https://oss.sonatype.org/content/groups/public/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.pom
  - https://jitpack.io/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.pom
  - https://bitbucket.org/kangarko/libraries/raw/master/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.pom
Required by:
    project : > com.github.kangarko:Foundation:6.8.3

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

https://hastebin.skyra.pw/miqupoqisu.gradle

**Comment by kangarko** [comment]
You need to model all dependencies and repositories from the foundation's pom.xml.
