### ISSUE TITLE
You need to allow set slots in later stage 

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/Foundation#299]
- 1) How it would benefit others? 
You will see the benefits in the current project I working on, as I don't have to not provide unnecessary things in the constructor. That is only needed if you create menus from 1 class. Also making it more flexible to work with all sorts of code and super has some big disadvantages as the value need to be provided direly either trough a new class or as constructor argument. 

- 2) What would happen if we won't implement this feature? How's your server being affected?
Just create more boilerplate code and create more work for the developer to null check. 

- 3) If suggesting something new - Can the old system be modified/improved instead?
Yeah it is what i suggest. I could if get some time over refactor this my self. But that will then be different version than the official one.

**Comment by kangarko** [comment]
Find another design. We already have three places to set a slot for a button, I dont see a point in adding more. Just pass in the data you need to the constructor as parameters and set the slots there. I've made very complex, animated plugins using this system, I believe there is a way around this. I can help you on the live call.
