### ISSUE TITLE
Menu setting player meta data

### ISSUE THREAD

**Issue by WhipMeGrandmaa** [kangarko/Foundation#301]
In the menu class, when it is displayed it sets the entire menu to the player's meta data. The issue is, if for example you want to make a leaderboard and you just reference a massive object in the buttons, it will still get put into the player's meta data and it can cause ram issues on the server.

**Comment by kangarko** [comment]
That is by design, then you please need to try adjusting your menu fields so that they store references and not the entire leaderboard.
