### ISSUE TITLE
1.20.4: Custom enchantment name not showing on all compatible items

### ISSUE THREAD

**Issue by Scraft161** [kangarko/Foundation#302]
Hi, I am running minecraft paper 1.20.4 with a custom plugin made with Foundation following the custom enchants tutorial, after getting it to work and trying it on a couple of items I noticed it doesn't show the lore on all items.

I am using the `minecraft:enchant` command which seems to work properly:
![command feedback: Applied enchantment enchantment.minecraft.soulbound III to Scraft161's item](https://github.com/user-attachments/assets/3783ddbf-bde3-42a9-b021-136a876db9f5 "command feedback: Applied enchantment enchantment.minecraft.soulbound III to Scraft161's item")

it then only displays on certain items:
![Enchanted Netherite Axe with no enchants listed](https://github.com/user-attachments/assets/821049bc-6fe3-49df-9d74-a9a1a0b009cd "Enchanted Netherite Axe with no enchants listed")
![Enchanted Wooden shovel with Soulbound III listed](https://github.com/user-attachments/assets/81b901ab-9eee-4400-8517-b8b48bda5e78 "Enchanted Wooden shovel with Soulbound III listed")
![Enchanted Netherite Sword with no enchantments listed](https://github.com/user-attachments/assets/b450cd12-709c-48e2-a346-57b8bd14ae59 "Enchanted Netherite Sword with no enchantments listed")
![Enchanted Wooden Sword with Soulbound III listed](https://github.com/user-attachments/assets/b029dbe5-39c6-4c0c-b6de-54018d25a268 "Enchanted Wooden Sword with Soulbound III listed")

some other items that I've noticed that don't list it are: `enchanted_book`, `netherite_chestplate`, and `turtle_shell`, this is by no means an exhaustive list, although I could check all the enchantable items if needed.

I am using Foundation 6.7.15 and ProtocolLib 5.2.0, I am however quite new to minecraft plugin development so it might be that I bunged something up, source code is available at [Scraft161/Simple-Soulbound](https://github.com/Scraft161/Simple-Soulbound) if you want a read through, the main plugin class is [/src/main/java/dev/scraft/SimpleSoulbound/Plugin.java](https://github.com/Scraft161/Simple-Soulbound/blob/master/src/main/java/dev/scraft/SimpleSoulbound/Plugin.java).

**Comment by kangarko** [comment]
Probably a MC or protocollib bug, unfortunately I dont have the the time constrains to debug this. Contributions are welcome.
