### ISSUE TITLE
Minecraft Version:1.20.1 Issue Title cannot start a plugin using foundation

### ISSUE THREAD

**Issue by LTAmjad** [kangarko/Foundation#303]
I am following yourm cowcannon plugin tutorial and im trying to us foundation with my plugin but its not letting me and gives me this error: https://pastebin.com/zdQE7tr3

**Comment by kangarko** [comment]
You need to shade Foundation to your jar according to https://github.com/kangarko/Foundation?tab=readme-ov-file#shading-important
