### ISSUE TITLE
1.16+ : How to add support to Kyori Advntr ( Specifically MiniMessage ) in Spigot JARs with Foundation

### ISSUE THREAD

**Issue by Shiftcoder94** [kangarko/Foundation#307]
**Kyori Advntr** or specifically **MiniMessage** provides a lot of ways to design a sample `TextComponent` with ease, so as `SimpleComponent ` in Foundation. But comparing the both, I had a question whether is it possible to add a deserialization functionality just like in MiniMessage???

For deserialization reference - https://docs.advntr.dev/minimessage/api.html.

**Comment by kangarko** [comment]
You can simply place minimessage as a dependency (or place paper-api since they include it) above foundation in your pom.xml
