### ISSUE TITLE
Library Limitation: Enchantments not Appearing on items (sometimes)

### ISSUE THREAD

**Issue by IIHERO4** [kangarko/Foundation#310]
So as started in [kangarko video for enchantments](https://youtu.be/1_W0ISi5ZbM?si=PIv53izBrvcYubpF), sometimes the correct item data is being sent to the client (not intercepted by foundation). After digging around in the minecraft protocol [1.20.4](https://wiki.vg/index.php?title=Protocol&oldid=7368) (searching the page for field `Slot`) , Seems that `SET_SLOT` & `WINDOW_ITEMS` should have been intercepted for editing the lore. Although i see @ [Foundation Packet Listener](https://github.com/kangarko/Foundation/blob/master/src/main/java/org/mineacademy/fo/plugin/FoundationPacketListener.java#L45) Only doing so for `SET_SLOT`. I kinda already added another listener that does the same for `WINDOW_ITEMS` and the enchantment lore seems consistent but was wondering if there was a reason it wasnt done in foundation (maybe breaking smth in some edge case idk)

**Comment by kangarko** [comment]
Thanks, will be pulling your PR, really appreciated your work!
