### ISSUE TITLE
1.21.1: FileNotFoundException: Libby Library Not Loading

### ISSUE THREAD

**Issue by Ultimating** [kangarko/Foundation#314]
Hello,

I'm currently using Foundation 6.9.2 and I have a user that has reported a FileNotFoundException that occurs on plugin startup that says the Libby Library jar Foundation uses isn't found. I'm not sure what the issue could be since I don't see it occur on my end. Attached is the exception sent to me.

Please let me know if anything else is needed. Thanks in advance!

[Exception](https://pastebin.com/ef7kFN2u)

**Comment by kangarko** [comment]
Fixed in 6.9.4. If you used SimplePlugin#loadLibrary please put your libs into libraries key of plugin.yml now
