### ISSUE TITLE
1.8.8: Very long startup server

### ISSUE THREAD

**Issue by epilepticseizureee** [kangarko/Foundation#316]
When starting the server, it takes too long to turn on, which is signaled by LagCatcher.
(start-engine took 1906.51 ms)

I attach server logs, the plugin is built using maven with clean compile package commands. 
latest.log - https://pastebin.com/6Tc6zJRU

If you don't use the library, the server starts and loads almost instantly. I checked various theories, tried to disable database and other functions, but unfortunately it didn't help.

Why, or rather what can cause this problem?

My pom.xml - https://pastebin.com/P4jT9eyY

**Comment by kangarko** [comment]
Fixed in 6.9.4. If you used SimplePlugin#loadLibrary please put your libs into libraries key of plugin.yml now
