### ISSUE TITLE
1.21: Alot of "Could not find ..." errors when running the server.

### ISSUE THREAD

**Issue by joshey40** [kangarko/Foundation#317]
When I am running the Server (in the IntelliJ IDE) I'm getting this Error message: https://pastebin.com/XdkE23xb that a bunch of plugins, like AuthMe, BentoBox, CitizensAPI, etc are missing. But I don't want to use those.

I'm not sure if it has to do with the way I implemented Foundation, since the setup guide was for maven and I'm using gradle, so I just did what the explanation said here: https://jitpack.io/#kangarko/Foundation/6.9.4

Btw, this is my build.gradle.kts: https://pastebin.com/2j0gEXxQ Not sure if this is helpful.

**Comment by joshey40** [comment]
Ok I think it has something to do with the Shading. But I couldn't find a solution yet, since with Gradle it seems like I don't have something like the pom.xml.

**Comment by StarozytnySky** [comment]
@joshey40 you can exclude all this plugins from Foundation in gradle by adding in your build.gradle.kts this:
```        
implementation("org.mineacademy:StarLibrary:6.9.4") {

            exclude("org.mineacademy.plugin", "*")
        }
```

**Comment by StarozytnySky** [comment]
Weird, im use like this for a long time and don't have any problems.
Maybe try reopen project or again reload changes in build.gradle.kts

**Comment by joshey40** [comment]
@StarozytnySky sorry for the late reply. I got back to the project today and tried it again and it works. I don't know what I did different last time. Thank you very much :)

**Comment by kangarko** [comment]
@joshey40 may you please share your gradle setup here, please? Or link to your repo? I'd love to show an example to all other people who're interested since we have had this question pop up a few times. Appreciated a lot!
