### ISSUE TITLE
1.8.8: Too long server startup

### ISSUE THREAD

**Issue by epilepticseizureee** [kangarko/Foundation#318]
Wrote one thread on this topic already, but never helped. The problem is that when using Foundation my plugin takes a very long time to start, about 15-20 seconds.

If I don't use Foundation, the plugin starts instantly.

There was a reply to my last topic that it was fixed, but as I saw it was not fixed.

I'm attaching pom.xml once again
https://pastebin.com/8SUdbXRX

**Comment by kangarko** [comment]
Please adjust your pom.xml according to mine at github.com/kangarko/plugintemplate, you dont need all of these exclusions there.

And then ZIP me your entire source code so I can try reproducing.

**Comment by kangarko** [comment]
Sure, so right now you just need to duplicate this line for all the dependencies you want included:

 <include>${foundation.path}:Foundation*</include>

For example:

 <include>it.unimi.dsi:fastutil</include>

Etc.

Hope that helps - apology for the delay in replying. Hopefully it will work now and let me know below if you need any more assistance.
