### ISSUE TITLE
1.21.1: ReflectionException

### ISSUE THREAD

**Issue by Ultimating** [kangarko/Foundation#319]
I was given a ReflectionException from one of my customers in regards to Foundation not finding the replaceFontImages method.

However, the method itself still exists on ItemsAdder API, so I'm not sure why the exception occurs.

They seem to be using ItemsAdder v4.0.2-beta-release-9 as I saw a feature request about this method on their GitHub in the version's changelog.

The exception is [here](https://bin.bloom.host/iqayosimem.md).

I've instructed them to downgrade ItemsAdder for now, but let me know if you need any additional details.

**Comment by kangarko** [comment]
Thanks, will be updating ItemsAdder shortly.

**Comment by Ultimating** [comment]
> Thanks, will be updating ItemsAdder shortly.

Any updates, @kangarko?
