### ISSUE TITLE
1.16.1: Placeholder API-2.10.8  Cannot Be Resolved

### ISSUE THREAD

**Issue by ItzRozzaDev** [kangarko/Foundation#32]
I am having trouble resolving PlaceholderAPI-**2.10.8,** this is weird as in foundation's pom file you are getting version **2.10.9-DEV-96**

My POM File: https://pastebin.com/Q3fhY6zu
Error: https://i.imgur.com/nC0Itpz.png

**Comment by kangarko** [comment]
Thanks, I added 2.10.8 back. Just go to your user folder, find the .m2 folder, inside of that navigate to org/mineacademy/plugin and remove PlaceholderAPI folder while having your IDE closed. Then reimport/update Maven project.

Closing, but let me know if the problem was resolved by commenting below.

**Comment by ItzRozzaDev** [comment]
I can now build my plugin but i am still getting this: https://i.imgur.com/5koIBsx.png. Also there are a few issues/questions I have with foundation that i would like to ask/show, so if its possible can we hope in a discord call and i can show you.

**Comment by kangarko** [comment]
Thanks, I fixed the POM warnings again. Please open your user folder, then navigate to .m2 folder, open org/mineacademy and remove the plugin folder. Finally, reimport/update your Maven project(s).

**Comment by kangarko** [comment]
For the other issues, I appreciate if you open a ticket for each one separately. It help us navigate through them, prioritize and save time. If something cannot absolutely be described in a medium other than video, you can use Loom.

**Comment by ItzRozzaDev** [comment]
Thank you the errors are now gone. I will make tickets for my following issues :)
