### ISSUE TITLE
Add Buttons an Array/List - MC 1.20.6

### ISSUE THREAD

**Issue by HomieLoverMC** [kangarko/Foundation#323]
Hello, I am currently developing a Loadout plugin to use with friends, and using Foundation, I've found it easy to set up and configure buttons within a Menu (thank you), however, due to the nature of my plugin, I want to add buttons dynamically using commands. I have most of this configured already, however, since I am using an ArrayList to store the buttons, I can't get the onClickedInMenu to register.  If I run the onClickedInMenu method somewhere in the code, everything works as intended, but physically left-clicking the button does nothing. I've put this as a question as I assume I'm doing something wrong, and any advice would be appreciated.

For further clarification, the code below works fine

```
testButton = new Button() {
            @Override
            public void onClickedInMenu(Player player, Menu menu, ClickType click) {
                (INSERT CODE)
            }

            @Override
            public ItemStack getItem() {
                return ItemCreator.of(CompMaterial.COAL, "Test Button").make();
            }
        };
```

But when I use arrays for the buttons, it appears correctly with the specific texture, I just can't click it: 

```
this.testButtons.add(new Button() {
            @Override
            public void onClickedInMenu(Player player, Menu menu, ClickType click) {
                (INSERT CODE)
            }

            @Override
            public ItemStack getItem() {
                return ItemCreator.of(CompMaterial.COAL, "Test Button").make();
            }
        });
```

Thank you for any help!

**Comment by MrDraqon** [comment]
Hey You should be able to overide getButtonsToAutoRegister() in your menu class it takes a List of Buttons after that the onClickedInMenu inside the buttons should be listening to the clicks

**Comment by HomieLoverMC** [comment]
Perfect, this worked! Thank you so much for your help, much appreciated!
