### ISSUE TITLE
Building with 6.9.7

### ISSUE THREAD

**Issue by cobrex1** [kangarko/Foundation#325]
I have been using foundation for my project. My last build used 6.9.2, so update the pom to 6.9.7 and the project will not build with the error

[ERROR] /F:/Minecraft Server Build projects/IdeaProjects/TownyMenu/src/main/java/me/cobrex/townymenu/plot/prompt/PlotSetTypePrompt.java:[6,32] cannot access org.bukkit.conversations.ConversationContext
  bad class file: C:\Users\graem\.m2\repository\io\papermc\paper\paper-api\1.21.1-R0.1-SNAPSHOT\paper-api-1.21.1-R0.1-SNAPSHOT.jar(org/bukkit/conversations/ConversationContext.class)
    class file has wrong version 65.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

I can use any version up to 6.9.5, so I am not sure why this is failing. Any help would be appreciated.

The project is using Java 1.8 and SDK 1.8

**Comment by kangarko** [comment]
Hello Graeme!

Please use Java 21 when you are compiling with Maven. In IntelliJ, this is under your Run Configuration under Java Options, manually select JDK 21.

![Screenshot 2024-09-28 at 09 43 48](https://github.com/user-attachments/assets/a60376b4-dc61-4ca4-be93-bf87e27fd990)
