### ISSUE TITLE
Add PlayerInteractAtEntityEvent to Tool class

### ISSUE THREAD

**Issue by rageyh** [kangarko/Foundation#326]
Hi, my idea was to implement “PlayerInteractAtEntityEvent” in Tool class. So when I extend the class I can handle interact of item with another entity. Is it possible?

**Comment by kangarko** [comment]
Any event can easily be added, just write your own listener class, then get the tool using the static method in Tool, cast it to your specific tool class - or make an abstract mytool extending the tool class - check if the tool is of that instance and cast to it, and call your event method.
