### ISSUE TITLE
SimplePlugin Error

### ISSUE THREAD

**Issue by cvboyer122** [kangarko/Foundation#33]
Hi there! I was having no problem building the project and running it on Minecraft yesterday until the evening. I keep getting this error.
https://pastebin.com/jHaxpUjG

I have made sure in my .m2 that everything is there, and it is. I checked multiple times that my pom is correct. It builds just fine but I get that error when I run in run/debug mode on IntelliJ.

**Comment by kangarko** [comment]
Please upload your pom.xml file, we recently had changes in how files are built: https://github.com/kangarko/Foundation#a-alternative-a-if-you-dont-have-foundation-on-your-computer

**Comment by cvboyer122** [comment]
https://pastebin.com/mcHnnTwV - I followed the directions but it "Cannot resolve org.mineacademy:Foundation:5.5.2" nor the "LATEST" keyword.

**Comment by Magnum97** [comment]
I am also having a problem with compile a plugin. I have not made anything for Minecraft in a few months and I see there are many Foundation changes this year.
@cvboyer122 Do you have Foundation downloaded and compiled on your computer? Or do you use the jitpack / github to collect and compile it? 
I have cloned the Foundation repo locally, thus I use `org.mineacademy:Foundation:5.5.2` in my build script. I had an error on every item in the Foundation/plugins category but after deleting everything inside ~/.m2/repository/org/mineacademy I ran `mvn clean install` on the latest (5.5.2) version of Foundation. Now I only have two errors, one for CMI-API and Multiverse-Core  https://hastebin.com/poradotiwa.coffeescript
If you use `com.github.kangarko:Foundation:5.5.2` try removing your local copy at `~/.m2/repository/com/github/kangarko/Foundation`.

**Comment by Magnum97** [comment]
I found a workaround. This is taken form the Foundation pom.xml in this repository:
```
		<dependency>
			<groupId>org.mineacademy.plugin</groupId>
			<artifactId>CMI-API</artifactId>
			<version>7.6.2.0</version>
		</dependency>
...
		<dependency>
			<groupId>org.mineacademy.plugin</groupId>
			<artifactId>Multiverse-Core</artifactId>
			<version>4.1.1-SNAPSHOT-787</version>
		</dependency>
```
Below are screenshots of the respective libraries' pom.xml from the mineacademy bitbucket repository. After editing the pom in my .m2 folder I am now able to compile as long as I pull from MavenLocal (I use Gradle) and not the bitbucket repository. 

![Screenshot from 2020-08-05 19-01-30](https://user-images.githubusercontent.com/39318657/89482363-9080c300-d74e-11ea-962a-61c7ed1f3c28.png)
![Screenshot from 2020-08-05 19-01-39](https://user-images.githubusercontent.com/39318657/89482366-924a8680-d74e-11ea-8ad3-15e28e7072ee.png)

**Comment by kangarko** [comment]
@cvboyer122 as it is written in the file, you must not use LATEST. It is something I use since I have Foundation physically on disk.

Instead, change it to latest version from https://github.com/kangarko/Foundation/releases.

Then you have to find <groupId>org.mineacademy</groupId> and replace with <groupId>com.github.kangarko</groupId> as stated on the main page.

@Magnum97 thanks for pointing out that the pom had invalid version, I fixed that. Please remove your .m2 again and it should download fine now.
