### ISSUE TITLE
1.21.3 - NoClassDefFoundError

### ISSUE THREAD

**Issue by LuuckA21** [kangarko/Foundation#330]
I'm using Foundation for Menu and when I click on an item this error occur

Foundation version: 6.9.9
Minecraft version: 1.21.3
Server: Paper 1.21.3-R0.1-SNAPSHOT

Error: https://pastebin.com/gZ0ZRkKa

**Comment by kangarko** [comment]
Sorry, need 1-2 more days to fix.

**Comment by kangarko** [comment]
Fixed
