### ISSUE TITLE
1.21.3: ConfigYaml Saving

### ISSUE THREAD

**Issue by tooobiiii** [kangarko/Foundation#338]
I noticed that saving the yaml config to file doesnt really work i mean it saves it somehow but the file doesnt change afterwards.

I save the value, no error. 
The yml file does not change at all.
But when i now get the value using T extends YamlConfig.get() it return the correct value??

**Comment by kangarko** [comment]
I would need to see your code to help

**Comment by tooobiiii** [comment]
Okay take a look at this then. Please bare with me i am pretty new to this 
https://github.com/MaceMC/OneBlock

**Comment by kangarko** [comment]
No problem. Which class it is? The Settings class you have is empty. I do not think it will work unless at least one value is specified. Also remove the "if (isSetDefault("Name"))" and rather use default params in get methods

**Comment by tooobiiii** [comment]
What does Settings class have to do with the YamlConfig? Thought the YamlConfig was a to handle n amounts of .yml files for e.g saving data to a file. Independent from the plugin config / settings.yml. 

I wanted to use this as an small data.yml with corresponding implementation in class "PlayerData"

**Comment by kangarko** [comment]
The Settings class uses YamlConfig, but I see I have misunderstood your comment.

Please use System.out.println or any other logger at the last line in onSave() and print "getMap("")" - that will tell you all the values that are about to get saved and you can diagnoze the root issue.

**Comment by tooobiiii** [comment]
Seems like there an issue with saveComments since when i have overwritten saveComments to be false everything worked fine,
With comments getMap() always returned null, without it actually returned something

**Comment by kangarko** [comment]
Thanks for letting me know! FYI comments are completely reworked in Foundation 7. Foundation 6 uses YamlComments class which comes from a third party, meaning if there is a problem like this we'd need to work with them to get it solved.
