### ISSUE TITLE
1.21.3: Simple Clans Dependency issue?

### ISSUE THREAD

**Issue by PaXo0** [kangarko/Foundation#340]
1) Put your Minecraft version in the title.
1.21.3

2) Be clear: What is your current situation, the desired situation, and your problem?
Failure to respove dependencies ( simpleclans:2.19.3-snapshot-418 )

3) If needed - upload any errors to pastebin.com.

https://pastebin.com/EL3Vs75D

Added foundation to a fresh install of Intellij Community Edition (minecraft paper 1.21.3) with a blank project and followed the instructions to add the nessecary dependencies. The only one that fails to resolve is SimpleClans-2.19.3-SNAPSHOT-418

**Comment by PaXo0** [comment]
It seem's it was flagged by windows security - should be fixed now

**Comment by kangarko** [comment]
Happy to hear it got resolved! Merry Christmas!
