### ISSUE TITLE
Removal of "vanish" metadata on PlayerUtil.normalize()

### ISSUE THREAD

**Issue by FeaturedSpace** [kangarko/Foundation#4]
This is something that I've noticed whilst using the Foundation library. I used the library to design a simplified Vanish plugin to teach one of my students. 

Basically, these lines make no sense at all:
```java
if (player.hasMetadata("vanished")) {
	final Plugin plugin = player.getMetadata("vanished").get(0).getOwningPlugin();

		player.removeMetadata("vanished", plugin);
	}

	for (final Player other : Remain.getOnlinePlayers())
		if (!other.getName().equals(player.getName()) && !other.canSee(player))
						other.showPlayer(player);
```

Now while this does "unvanish" players, that is game breaking to most vanish plugins, who keep an internal state of who is vanished so that server-switches and other game events do not break vanish.

It is my opinion that this should be removed from the normalize method. Either that or all metadata should be removed from the player, as that would be "normalizing" them.

Please comment on your thoughts!

Thanks,
Noah

**Comment by FeaturedSpace** [comment]
@kangarko

**Comment by kangarko** [comment]
I have extended that method to include a way of specifying whether or not to remove vanish, thanks!

https://github.com/kangarko/Foundation/commit/e332a18b296114b2fd79dce2a70b9e6cccdfcf07
