### ISSUE TITLE
CompMaterial lacking items from MC 1.14 and up

### ISSUE THREAD

**Issue by kangarko** [kangarko/Foundation#41]
I added few requested but there is more: https://github.com/kangarko/Confiscate/issues/97

**Comment by md5sha256** [comment]
Is there a given convention for the "legacy" names for new blocks (such as bell --> flower pot)?

**Comment by ItzRozzaDev** [comment]
Is there a list of missing materials?

**Comment by md5sha256** [comment]
My current diff is like 50 lines for 1.14?

**Comment by ItzRozzaDev** [comment]
I will look in to this tomorrow as. I am busy for the rest of today 😝

**Comment by kangarko** [comment]
Thanks, just to clarify all MC 1.14 and 1.15 items are added, and we just need to finish the 1.16 ones?

**Comment by md5sha256** [comment]
Ah yes I forgot about 1.16 - whoops (lol).

**Comment by md5sha256** [comment]
Considering most of the 1.16 changes arise from the nether, should "legacy" blocks be things like netherrack as opposed to stone?

**Comment by md5sha256** [comment]
This can probably be closed after #44 is merged in

**Comment by kangarko** [comment]
Thanks! Yes just use what makes sense, netherrack makes more sense in the nether than stone.
