### ISSUE TITLE
HEX codes in JSON only support 1 color

### ISSUE THREAD

**Issue by kangarko** [kangarko/Foundation#45]
This commit is limited to 1 color only, that is the last color: https://github.com/kangarko/Foundation/commit/ea1bda5e872a3540c3c5e99ab3dd80eb8d69e7b0

Steps to reproduce: Call sendJson() on a message containing {test} with SerializedMap.orArray("test", "{#00c792}hello {#5b04b3}world")

**Comment by md5sha256** [comment]
So when I placed in `Remain.sendJson(sender, SerializedMap.of("text", "{#00c792}hello {#5b04b3}world").toJson());` I get white text, which is not what we want. However, when I try this 
`Remain.sendJson(sender, SerializedMap.of("test", "{#00c792}hello {#5b04b3}world").toJson());` I get an error, but the colors are parsed in the error message.

Image of what I am descrbing can be found here: [https://prnt.sc/txbta6](url)

**Comment by FeaturedSpace** [comment]
@kangarko Out of curiosity, is this a feature that is possible in all versions of MC? I honestly didn't think it was possible.

**Comment by md5sha256** [comment]
HEX on the client is only 1.16+

**Comment by FeaturedSpace** [comment]
Ahh, that's frustrating to me. Please, Mojang, fix combat so all servers can go up to the latest version. Going from 16 colors to 16 million is a huge jump.

**Comment by md5sha256** [comment]
With the current setup, there is no way to make a `{hex} message {anotherHex} message2` work as you would require 2 components, one for each color. Thus, I've devised a new approach for this and will PR once complete.

**Comment by md5sha256** [comment]
Should be resolved by #46
