### ISSUE TITLE
Command Group Help Message Idea

### ISSUE THREAD

**Issue by ItzRozzaDev** [kangarko/Foundation#47]
I have an idea for command groups. My idea is a page system to the help message. For example 10 commands per page (this could be customised as well). Please let me hear what you think of this.

This feature will make it so players using plugins with foundation wont get chat spammed if a command group has many commands.

**Comment by lackoSK** [comment]
Hey! I've already planned this feature :) (was in TODO list)
I hope it gets added!

**Comment by kangarko** [comment]
Yep, sounds very nice indeed. I'm definitely leaving this open for implementation.

**Comment by kangarko** [comment]
Thanks, added:

![a](https://i.imgur.com/4tRAf9F.png)
