### ISSUE TITLE
1.16.1: Loading MapList from YamlConfig

### ISSUE THREAD

**Issue by lackoSK** [kangarko/Foundation#68]
Hey! 

I'm facing an issue with loading Maps using `getMapList()` method. 

The code for loading is bounties... https://pastebin.com/azSKeius
The error... https://pastebin.com/8xZ60MZa

The config file looks like:
![image](https://user-images.githubusercontent.com/53174757/90317548-aa7a8c80-df2a-11ea-8cdb-5f55e5bf762f.png)

Any ideas, how do I fix it? 

Thanks
Ladislav

**Comment by Magnum97** [comment]
If I'm not mistaken, your key `Bounties` is a ConfirugationSection. To load a map .. and I have not tested this yet just eyeballing it - you would `getMap("Bounties.<UUID>")` which should return a map of key, value pairs.

**Comment by kangarko** [comment]
Thanks @Magnum97 for the answer that is absolutely correct :)
