### ISSUE TITLE
1.16.1-R0.1-SNAPSHOT: SimpleEnchantment name duplicated

### ISSUE THREAD

**Issue by MyNameIsAres** [kangarko/Foundation#74]
1.16.1-R0.1-SNAPSHOT
Foundation version: 5.6.3

Going through the lesson on creating custom enchantments. If I pass a name into the constructor:

`private BlackNovaEnchant() {
        super("Black Nova", 5);
    }
`
It will duplicate the text "Black Nova I" (I = Level) in the item, upon using the custom enchantment command. When I first type the '/ce' command, it will create the sword with "Black Nova I" 3x. It will then duplicate the name a couple more times, every so often.

In addition to this, it will also duplicate the name if you click on the sword, so it's now free to be moved around in your inventory, and then place it again. This results in a massive list of ''Black Nova I" names. 

I've copied and pasted the code from your original project in the download button. However, this didn't resolve the issue either.

Below is a screenshot to further demonstrate what I'm referring to.
![2020-08-21_13 44 58](https://user-images.githubusercontent.com/32432637/90887390-8ef10500-e3b4-11ea-861e-75e3304cd9d8.png)

**EDIT**
I understand a previous Github issue reported this as well. In issue #71  It might be the exact same issue. It was supposedly fixed in version 5.6.3. However, I'm still experiencing that issue. Could it be that I messed up my POM file?https://pastebin.com/Dp4vBQrv
I ran a few Maven commands to see if there were any build issues, but there weren't.

**EDIT 2**
Created a blank project. Copied and pasted the (relevant) code from Matej's Orion code. The issue was still there.

**Comment by Magnum97** [comment]
I can not say what is happening without seeing your code. I know Gradle better than Maven, but there are no errors that are obvious to me in your pom.xml. 

 I used the code from #71 to make [this](https://github.com/Magnum97/BlackEnchant) which works in my testing. Maybe the code there will help you. I hope.

**Comment by MyNameIsAres** [comment]
The problem has been resolved. I was working out a different issue, and removed all plugin files along with the paper jar and bat file to a different server folder. Came back to debug the project and it has resolved itself. 

Thanks to @Magnum97 for responding anyway. 👍
