### ISSUE TITLE
Multiple HEX colors not parsed properly

### ISSUE THREAD

**Issue by kangarko** [kangarko/Foundation#75]
When a new HEX color is added to a JSON string (serialized message) that is sent over BungeeCord or within the server as a component (see Remain.sendComponent), only 1 HEX color is supported. More colors will result in colors not being properly placed:

![a](https://i.imgur.com/d7ta48S.png)

**Comment by james090500** [comment]
As mentioned in kangarko/ChatControl-Pro#1853 this isn't just HEX but also normal minecraft colour codes as well. Funnily enough using capitals in nickname colours still work. 

eg; &AJames shows a light green "James" but &aJames shows white "James". Numbered colour nicknames are always white; eg &1

**Comment by SiuanSong** [comment]
Experiencing the same as @james090500

**Comment by kangarko** [comment]
@md5sha256 @FeaturedSpace one of you guys did a pull request that partially solved this but I had to revert it due to other problems it caused, may you please have a look into it? Many thanks!

**Comment by kangarko** [comment]
Closing for now, I'll have a look later
