### ISSUE TITLE
1.16.2 (but I guess any version): SkullCreator#itemWithBase64 throws NoSuchMethodException

### ISSUE THREAD

**Issue by LenjoyOfficial** [kangarko/Foundation#77]
I am trying to create a player head with custom texture by calling `SkullCreator#itemWithBase64(ItemStack, String)`, and `makeProfile(String base64)` throws a NoSuchMethodException:
https://pastebin.com/hc8JjWJj

It's because `makeProfile` tries to create a new Property with a single String parameter. The Property class only has `(String name, String value)` and `(String name, String value, String signature)` constructors. From what I've learned, the solution would be to change these lines:
```
final Class<?> propertyClass = ReflectionUtil.lookupClass("com.mojang.authlib.properties.Property");
final Object property = ReflectionUtil.instantiate(propertyClass.getConstructor(String.class), b64);
```
to 
```
final Class<?> propertyClass = ReflectionUtil.lookupClass("com.mojang.authlib.properties.Property");
final Object property = ReflectionUtil.instantiate(propertyClass.getConstructor(String.class, String.class), "textures", b64);
```
because as far as I know, the constructor arguments would be "textures" and the Base64 value.

Feel free to correct me if I'm wrong in any of these!

**Comment by LenjoyOfficial** [comment]
And also, even after using the fixed version, now this line threw a NoSuchMethodException:
`propertyMap.getClass().getMethod("put", String.class, propertyClass).invoke(propertyMap, "textures", property);`
https://pastebin.com/pxNz2UeG

I changed it to invoke the `put` method from the ReflectionUtil class, and this fixed it!
`ReflectionUtil.invoke("put", propertyMap, "textures", property);`

**Comment by kangarko** [comment]
Thank you for providing a fix! Please go ahead and make a pull request, I will merged it :)

**Comment by LenjoyOfficial** [comment]
Thank you! Made a pull request.
