### ISSUE TITLE
Minecraft Version: 1.8.8: Unbreakable tag doesnt apply

### ISSUE THREAD

**Issue by PitRemake** [kangarko/Foundation#81]
When i'm trying to use the .unbreakable() method in ItemCreator.of then it just does nothing. 
Heres an example code i tried:
`ItemStack mysticsword = ItemCreator.of(CompMaterial.GOLDEN_SWORD, "&eMystic Sword").unbreakable(true).build().make();`
When i give someone this item in the game it still breaks. Please fix.

**Comment by FeaturedSpace** [comment]
Yes, this issue has come up in the past. My team moved around it by simply implementing the normal Bukkit (deprecated) way of doing it, perhaps you can do the same?

**Comment by PitRemake** [comment]
Whats the normal bukkit way of doing it? So i cant use the ItemCreator then or how do i do it?

**Comment by FeaturedSpace** [comment]
Google is your friend :)

**Comment by PitRemake** [comment]
I know how to do it my question is if i can still use the ItemCreator or if i need to do the very normal bukkit way ?

**Comment by PitRemake** [comment]
Anyway they should really just fix this issue its been there for months and its a major issue

**Comment by FeaturedSpace** [comment]
You can of course still use the ItemCreator. Then just apply the unbreakable meta using Spigot's API.

It definitely does need to be fixed, but if you look in the source, nothing appears to be wrong...

**Comment by kangarko** [comment]
Can you enlighten me on how to set the unbreakable flag on 1.8.8? Haven't googled yet but I'll definitely patch this along with HEX armor colors for 1.16

**Comment by PitRemake** [comment]
private void setUnbreakable(ItemStack item) {
		ItemMeta meta = item.getItemMeta();

		meta.spigot().setUnbreakable(true);

		item.setItemMeta(meta);
	}
well i used this method before hope it helps

**Comment by PitRemake** [comment]
Also i would like hex armor colors in 1.8 aswell if possible :p

**Comment by FeaturedSpace** [comment]
@PitRemake HEX codes are only available in 1.16+, it's a new feature in Minecraft.

**Comment by PitRemake** [comment]
No they arent? I'm using hex codes in 1.8.8 for leather pants.

**Comment by kangarko** [comment]
Attempted to solve this, looks like it's working now:

https://github.com/kangarko/Foundation/commit/49bffdb8b9d5aa3ba50a39a86053c3e4665a6b48
 
<img width="758" alt="Skjermbilde 2020-10-27 kl  17 47 12" src="https://user-images.githubusercontent.com/1918426/97334015-80274280-187c-11eb-8f46-65e07aa53625.png">

You can just download the latest Foundation from its source.
