### ISSUE TITLE
Add custom colors to ItemCreator for leather armor

### ISSUE THREAD

**Issue by PitRemake** [kangarko/Foundation#82]
1)
Currently you can only color leather gear basically with the default chat colors which looks very ugly on armor in my opinion. It would be VERY helpful if you could add a way to add custom hex colors to leather armor so you can set them to any color which leaves a LOT more room for custom / special / armor gear than if you only have a few chatcolors available. I believe a lot of people could benefit from it because when you have many custom items in the game especially custom armor then its a lot easier for players to tell them apart if they have a greater and more bright color range. Most chatcolors look rather grayish and ugly on armor, i prefer pure red and other pure colors because it looks a lot better.

2) 
I basically can't implement any custom armor for now because there are like 3-4 chatcolors that even look remotely good on armor so theres no point even adding custom armor because its so limited visually.

3) 
I'm not sure but it shouldn't be too hard to just add a method that lets you change the hex color of it because thats very easily possible in bukkit/spigot. I would use it myself but then i couldn't use the itemcreator anymore which would be a whole lot more work defining all the items.

**Comment by kangarko** [comment]
Added. Use CompColor.fromName("#123456")

Until Foundation version updates you have to pull the latest source to use this.

**Comment by kangarko** [comment]
https://github.com/kangarko/Foundation/commit/4c96836b2356da5dd81a16e329c496799fc52a28
