### ISSUE TITLE
Common method: get World object by Name or UUID

### ISSUE THREAD

**Issue by 3DSX** [kangarko/Foundation#83]
1) How it would benefit others? (Not just you, but 1,000s of other people using the same plugin.)
Getting a world object by a String or UUID (overload)
2) What would happen if we won't implement this feature? How's your server being affected?
I won't be affected, it's just for saving some minutes when we want to perform this action, mostly in searching the Bukkit method for it.
3) If suggesting something new - Can the old system be modified/improved instead?
There is a function called getWorldNames but the implementation of that would just mostly be for checking if the given string is being used for the name of a world as it just returns a list of strings.

These 2 new methods will return the world you want if exists, passing the name or UUID, otherwise returns null. Added the necessary annotations.

```java
	@Nullable
	public static World getWorldByName(final @NotNull String worldName) {
		return Bukkit.getServer().getWorld(worldName);
	}

	@Nullable
	public static World getWorldByUUID(final @NotNull UUID worldUUID) {
		return Bukkit.getServer().getWorld(worldUUID);
	}
```

**Comment by kangarko** [comment]
Hi there,

Thanks for suggesting this. I appreciate this however for the time being we'd like to focus on adding more complex functions than reducing 3 calls to 2 or those that are not supplied within the native API what so ever. 

Matej
