### ISSUE TITLE
Ability To set a ItemStack to the BackReturnButton

### ISSUE THREAD

**Issue by ItzRozzaDev** [kangarko/Foundation#84]
I would like to set custom skull for a back button, and with the current setTitle, setMaterial and setLore method, this is not a option. So mu suggestion is you add another method that allows for setting of ItemStacks as well.

This would be nice to you can create nice looking back button with custom heads.

**Comment by kangarko** [comment]
Thanks, however we need to maintain backward compatibility with Project Orion so I avoid any breaking / workaround-type changes like this. You can just copy the code for the return button from Foundation into your own code and change what you need :)

**Comment by ItzRozzaDev** [comment]
Okay, thanks anyway :)
