### ISSUE TITLE
(1.15.2/1.16.3* known): NoSuchMethodError on getConfig in SimpleYaml

### ISSUE THREAD

**Issue by MyNameIsAres** [kangarko/Foundation#90]
I'm trying to use the getConfig() method from Foundation. I tested the method in two projects. The first project is built with the latest version of Foundation and the Minecraft version is 1.15.2. The second project is one version prior to the current release of Foundation and the Minecraft version is 1.16.3

When I use the method I receive the following error: 
https://pastebin.com/AFfZDRev

I'm using the method in a YamlConfig extended class with an Object type property. In my onLoadFinish method, I call it `test = getConfig.get("Test");` (test is an Object).

Could be using this method incorrectly but I don't see cause for the error to pop up.

**Comment by kangarko** [comment]
Seems like your project actually lacks this method, I'm unable to help with Foundation forks sorry. Decompile the final jar and see if the method is actually there. Check your maven shade plugin.

**Comment by MyNameIsAres** [comment]
Hello,

The Foundation library used is not a fork, but rather the authentic Foundation library. When I inspect the class the method is there. The method continues to be fired.

**Comment by kangarko** [comment]
Can you test on Paper not Cauldron? I know Cauldron does some reflection hacking to load Spigot plugins...

**Comment by MyNameIsAres** [comment]
Is Cauldron a fork of Spigot? I'm using Paper not Cauldron. The 'Cauldron' is just a package name in my plugin.

**Comment by kangarko** [comment]
Got it, well that doesn't change that the method cannot be found at the runtime level, I'm afraid I can't help with this since I never had this problem myself or reported
