### ISSUE TITLE
Your Suggestion Title

### ISSUE THREAD

**Issue by ItzRozzaDev** [kangarko/Foundation#96]
Adding the following  Common.tellReplaced to SimpleCommand would allow devs to use Common#tellReplaced without needing to specify the command sender. 

`
protected void tellReplaced(final String message, final Object... replacements) {
		tell(Replacer.replaceArray(message, replacements));
}
`

**Comment by kangarko** [comment]
Thanks added! Damn I just pushed a new version, well it will come in the next one :)

**Comment by ItzRozzaDev** [comment]
@kangarko You can also add to Common
 `public static void broadcastReplaced(final String message, final Object... replacements) {
		Common.broadcast(Replacer.replaceArray(message, replacements));
	}`

**Comment by kangarko** [comment]
Sure :)
